// Trigonometri Yolu — soru bankası (30 kolay, 30 orta, 30 zor)
const questions = {
    easy: [
        { question: "sin 45° değeri kaçtır?", options: ["1/2", "√2/2", "√3/2", "1"], correct: 1 },
        { question: "cos 0° değeri kaçtır?", options: ["0", "1/2", "1", "-1"], correct: 2 },
        { question: "tan 0° değeri kaçtır?", options: ["1", "0", "Tanımsız", "-1"], correct: 1 },
        { question: "sin(π/4) değeri kaçtır?", options: ["√2/2", "1/2", "√3/2", "1"], correct: 0 },
        { question: "cos(π/2) değeri kaçtır?", options: ["1", "-1", "0", "1/2"], correct: 2 },
        { question: "cot 45° değeri kaçtır?", options: ["0", "1", "√3", "1/√3"], correct: 1 },
        { question: "sec 60° değeri kaçtır?", options: ["2", "√2", "2/√3", "1/2"], correct: 0 },
        { question: "cosec 30° değeri kaçtır?", options: ["2", "√2", "1/2", "√3"], correct: 0 },
        { question: "sin(-90°) değeri kaçtır?", options: ["1", "0", "-1", "1/2"], correct: 2 },
        { question: "cos(-60°) değeri kaçtır?", options: ["-1/2", "1/2", "-√3/2", "√3/2"], correct: 1 },
        { question: "450° lik açının esas ölçüsü kaç derecedir?", options: ["90", "45", "180", "270"], correct: 0 },
        { question: "-120° lik açının esas ölçüsü kaç derecedir?", options: ["120", "240", "60", "300"], correct: 1 },
        { question: "(1 - cos²x) ifadesinin eşiti nedir?", options: ["sin²x", "cos²x", "1", "tan²x"], correct: 0 },
        { question: "sinx / cosx ifadesinin eşiti nedir?", options: ["cotx", "secx", "tanx", "cosecx"], correct: 2 },
        { question: "1 + tan²x ifadesinin eşiti nedir?", options: ["sec²x", "cos²x", "cosec²x", "sin²x"], correct: 0 },
        { question: "sin 120° değeri kaçtır?", options: ["√3/2", "1/2", "-1/2", "-√3/2"], correct: 0 },
        { question: "cos 150° değeri kaçtır?", options: ["1/2", "-1/2", "-√3/2", "√3/2"], correct: 2 },
        { question: "tan 135° değeri kaçtır?", options: ["1", "-1", "√3", "0"], correct: 1 },
        { question: "sin(x) = 0 denkleminin genel çözümü hangisidir?", options: ["x = kπ", "x = π/2 + kπ", "x = π/4 + kπ", "x = 2kπ"], correct: 0 },
        { question: "cos(x) = 0 denkleminin genel çözümü hangisidir?", options: ["x = kπ", "x = π/2 + kπ", "x = π/4 + kπ/2", "x = 2kπ"], correct: 1 },
        { question: "Birim çemberde 90° açının uç noktası hangisidir?", options: ["(1,0)", "(0,1)", "(-1,0)", "(0,-1)"], correct: 1 },
        { question: "sin30° + cos60° toplamı kaçtır?", options: ["0", "1", "1/2", "√3"], correct: 1 },
        { question: "tan45° · cot45° kaçtır?", options: ["0", "2", "1", "-1"], correct: 2 },
        { question: "arcsin(1/2) (dar açı) kaç derecedir?", options: ["30", "45", "60", "90"], correct: 0 },
        { question: "arccos(0) (dar açı) kaç derecedir?", options: ["0", "30", "60", "90"], correct: 3 },
        { question: "2sinx = 1 ise sinx kaçtır? (0 < x < π)", options: ["1", "1/2", "√3/2", "-1/2"], correct: 1 },
        { question: "cosx = -1/2 ise [0, 2π] aralığındaki çözüm kümesi hangisidir?", options: ["π/3, 5π/3", "2π/3, 4π/3", "π/6, 7π/6", "π/4, 3π/4"], correct: 1 },
        { question: "sin²30° + cos²30° kaçtır?", options: ["0", "1/2", "1", "√3/2"], correct: 2 },
        { question: "(secx)(cosx) ifadesinin değeri kaçtır?", options: ["tanx", "1", "sinx", "cotx"], correct: 1 },
        { question: "π radyan kaç dereceye eşittir?", options: ["90", "180", "270", "360"], correct: 1 }
    ],
    medium: [
        { question: "sin(75°) ifadesinin değeri hangisidir?", options: ["(√6+√2)/4", "(√6-√2)/4", "√3/2", "1/2"], correct: 0 },
        { question: "cos(15°) ifadesinin değeri hangisidir?", options: ["(√6+√2)/4", "(√6-√2)/4", "√2/2", "1/2"], correct: 0 },
        { question: "sin2x = 2sinx·cosx olduğuna göre sin(60°) kaçtır?", options: ["1/2", "√3/2", "1", "√3"], correct: 1 },
        { question: "cos2x = cos²x - sin²x olduğuna göre cos(60°) kaçtır?", options: ["-1/2", "1/2", "√3/2", "0"], correct: 1 },
        { question: "tan(75°) değeri kaçtır?", options: ["2+√3", "2-√3", "√3", "1"], correct: 0 },
        { question: "sinx·cosx = 1/4 ise sin2x kaçtır?", options: ["1/4", "1/2", "1", "√2/2"], correct: 1 },
        { question: "cos²x - sin²x = 1/2 ise cos2x kaçtır?", options: ["1/2", "-1/2", "√3/2", "0"], correct: 0 },
        { question: "sinx + cosx = √2 ise (0 ≤ x ≤ π/2) x kaç derecedir?", options: ["30", "45", "60", "90"], correct: 1 },
        { question: "tanx = -1 ve π/2 < x < π ise x kaç derecedir?", options: ["45", "135", "225", "315"], correct: 1 },
        { question: "sin(π - x) ifadesinin eşiti nedir?", options: ["-sinx", "sinx", "cosx", "-cosx"], correct: 1 },
        { question: "cos(π + x) ifadesinin eşiti nedir?", options: ["cosx", "-cosx", "sinx", "-sinx"], correct: 1 },
        { question: "tan(π - x) ifadesinin eşiti nedir?", options: ["tanx", "-tanx", "cotx", "-cotx"], correct: 1 },
        { question: "(1 + cos2x) / 2 ifadesinin eşiti nedir?", options: ["sin²x", "cos²x", "tan²x", "sec²x"], correct: 1 },
        { question: "sin²x / (1 + cosx) sadeleşince hangisine eşittir?", options: ["1 - cosx", "1 + cosx", "sinx", "cosx"], correct: 0 },
        { question: "cos(210°) değeri kaçtır?", options: ["√3/2", "-√3/2", "-1/2", "1/2"], correct: 1 },
        { question: "sin(300°) değeri kaçtır?", options: ["√3/2", "-√3/2", "1/2", "-1/2"], correct: 1 },
        { question: "cot(π/3) değeri kaçtır?", options: ["√3", "1/√3", "1", "-√3"], correct: 1 },
        { question: "sec(45°) değeri kaçtır?", options: ["√2", "2", "1", "√3"], correct: 0 },
        { question: "sinx = cosx denkleminin [0, 2π) çözüm kümesi hangisidir?", options: ["π/4, 5π/4", "π/4, 3π/4", "π/2, 3π/2", "π/6, 7π/6"], correct: 0 },
        { question: "2cosx - √3 = 0 denkleminin [0, 2π) çözüm kümesi hangisidir?", options: ["π/6, 11π/6", "π/3, 5π/3", "π/4, 7π/4", "π/2, 3π/2"], correct: 0 },
        { question: "sin(2x) = 1 denkleminin [0, π) çözümü hangisidir?", options: ["π/4", "π/2", "π/8", "π/6"], correct: 0 },
        { question: "f(x) = sin(2x) fonksiyonunun periyodu kaçtır?", options: ["2π", "π", "π/2", "4π"], correct: 1 },
        { question: "f(x) = cos(4x) fonksiyonunun periyodu kaçtır?", options: ["π/2", "π", "2π", "4π"], correct: 0 },
        { question: "(sin50° + sin10°) / (cos50° + cos10°) ifadesinin değeri kaçtır?", options: ["tan30°", "tan20°", "cot20°", "tan40°"], correct: 0 },
        { question: "cos70°·cos20° - sin70°·sin20° ifadesinin değeri kaçtır?", options: ["1/2", "√3/2", "√2/2", "0"], correct: 3 },
        { question: "√(1 - sin²x) (x dar açı) ifadesinin eşiti nedir?", options: ["sinx", "cosx", "tanx", "secx"], correct: 1 },
        { question: "sinx·cosecx + cosx·secx toplamı kaçtır?", options: ["0", "1", "2", "tanx"], correct: 2 },
        { question: "tanx + cotx = 2 ise tan²x + cot²x kaçtır?", options: ["2", "3", "4", "5"], correct: 0 },
        { question: "arcsin(-√3/2) ([-π/2, π/2]) değeri kaçtır?", options: ["-π/3", "π/3", "-π/6", "π/6"], correct: 0 },
        { question: "cos(2·arcsin(3/5)) ifadesinin değeri kaçtır?", options: ["7/25", "-7/25", "24/25", "-24/25"], correct: 0 }
    ],
    hard: [
        { question: "ABC üçgeninde a = 5, b = 7, C = 60° ise c² kaçtır? (kosinüs teoremi)", options: ["39", "49", "59", "69"], correct: 0 },
        { question: "ABC üçgeninde |a| = 8, |b| = 6, |c| = 10 ise cosA kaçtır?", options: ["1/2", "4/5", "3/5", "√3/2"], correct: 2 },
        { question: "sin75°·cos15° + cos75°·sin15° ifadesinin değeri kaçtır?", options: ["1/2", "√2/2", "√3/2", "1"], correct: 3 },
        { question: "cos(105°) ifadesinin değeri hangisidir?", options: ["(√6+√2)/4", "-(√6+√2)/4", "(√6-√2)/4", "-(√6-√2)/4"], correct: 3 },
        { question: "tan(15°) değeri kaçtır?", options: ["2-√3", "2+√3", "√3-1", "√3+1"], correct: 0 },
        { question: "sin3x = sinx denkleminin genel çözüm kümesi hangisidir?", options: ["x = kπ", "x = kπ/2", "x = kπ veya x = π/3 + kπ", "x = π/6 + kπ"], correct: 2 },
        { question: "cos2x = sinx denkleminin [0, 2π) aralığında kaç çözümü vardır?", options: ["2", "3", "4", "5"], correct: 1 },
        { question: "3sinx + 4cosx ifadesinin en büyük değeri kaçtır?", options: ["3", "4", "5", "7"], correct: 2 },
        { question: "sinx + √3cosx = 2 ise x (dar açı) kaçtır?", options: ["π/6", "π/3", "π/4", "π/2"], correct: 1 },
        { question: "tanx = 2 ise sin2x kaçtır?", options: ["4/5", "3/5", "2/5", "1/5"], correct: 0 },
        { question: "cotx = 3/4 ise sin2x kaçtır?", options: ["24/25", "7/25", "-24/25", "12/25"], correct: 0 },
        { question: "(sinx + cosx)² = 2 ise sin2x kaçtır?", options: ["0", "1", "-1", "1/2"], correct: 1 },
        { question: "cos(arctan(5/12)) ifadesinin değeri kaçtır?", options: ["12/13", "5/13", "5/12", "12/5"], correct: 0 },
        { question: "sin(arccos(4/5)) ifadesinin değeri kaçtır?", options: ["3/5", "4/5", "5/3", "4/3"], correct: 0 },
        { question: "Dik üçgende |AB| = 6, |AC| = 8, m(A) = 90° ise |BC| kaç birimdir?", options: ["10", "12", "14", "2√7"], correct: 0 },
        { question: "R = 2 çevrel çemberde 60° lik merkez açının gördüğü yay uzunluğu kaçtır?", options: ["π/3", "2π/3", "π", "4π/3"], correct: 1 },
        { question: "sin10°·sin50°·sin70° ifadesinin değeri kaçtır?", options: ["1/8", "1/4", "√3/8", "1/2"], correct: 0 },
        { question: "cos20°·cos40°·cos80° ifadesinin değeri kaçtır?", options: ["1/8", "1/4", "√3/8", "1/16"], correct: 0 },
        { question: "sin⁴x - cos⁴x ifadesinin eşiti hangisidir?", options: ["sin2x", "cos2x", "sin²x - cos²x", "sin²x + cos²x"], correct: 2 },
        { question: "Sinüs teoremine göre b = 8, B = 30°, A = 45° ise a kaçtır?", options: ["4√2", "8√2", "4", "8"], correct: 0 },
        { question: "Alanı 24, iki kenarı 6 ve 8 olan üçgende aralarındaki açı kaç derecedir?", options: ["30", "45", "60", "90"], correct: 3 },
        { question: "cos²x = 3/4 denkleminin [0, π) çözüm kümesi hangisidir?", options: ["π/6, 5π/6", "π/3, 2π/3", "π/4, 3π/4", "π/2"], correct: 1 },
        { question: "sinx + sin3x = 2sin2x·cosx eşitliği sadeleştirildiğinde hangi ifade elde edilir?", options: ["2sin2x·cosx", "2cos2x·sinx", "sin4x", "cos4x"], correct: 0 },
        { question: "tan(π/8) değeri kaçtır?", options: ["√2 - 1", "√2 + 1", "1", "√3 - 1"], correct: 0 },
        { question: "0 < x < π/2 ve tanx = 3/4 ise sinx kaçtır?", options: ["3/5", "4/5", "5/3", "4/3"], correct: 0 },
        { question: "cos(180°) ifadesinin değeri kaçtır?", options: ["-1", "-1/2", "0", "1"], correct: 0 },
        { question: "sinx·sin(60°-x)·sin(60°+x) ifadesinin eşiti hangisidir?", options: ["(sin3x)/4", "sin3x", "(cos3x)/4", "sinx"], correct: 0 },
        { question: "2sin²x - 3sinx + 1 = 0 denkleminin [0, 2π) aralığında kaç çözümü vardır?", options: ["2", "3", "4", "5"], correct: 1 },
        {
            question: "Şekildeki ABC üçgeninde m(BÂC) = 45°, |AB| = 40 cm ve |AC| = 30√2 cm olduğuna göre |BC| = x kaç cm'dir?",
            image: "images/zor4.png",
            options: ["10√10", "30", "10√11", "20"],
            correct: 0
        },
        {
            question: "Şekildeki ABC üçgeninde |AC| = 20 cm, |BC| = 60 cm ve m(BÂC) = x + 90° olduğuna göre sinx kaçtır?",
            image: "images/zor5.png",
            options: ["1/√10", "1/√5", "1/3", "1/2"],
            correct: 0
        }
    ]
};
